[package]
name = "parser_macros"
version = "0.1.0"
authors = ["Tim Vermeulen <tvermeulen@me.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"

[dependencies.syn]
version = "0.15.26"
features = ["full"]